# Generated by Django 4.2.3 on 2023-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lwin18', models.IntegerField(max_length=18)),
                ('abv', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('submittor_ip', models.GenericIPAddressField()),
                ('submittor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
