# Generated by Django 4.2.3 on 2024-04-13 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abv', '0003_rename_lwin18_abv_lwin11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abv',
            name='submittor_email',
        ),
        migrations.AlterField(
            model_name='abv',
            name='abv',
            field=models.FloatField(max_length=5, validators=[django.core.validators.RegexValidator(message="Must be a float from 0.0–100.0 with 1 decimal place, e.g. '0.0', '14.0', '100.0'.", regex='^\\d{1,3}\\.\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='abv',
            name='lwin11',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Must be an 11-digit integer.', regex='^\\d{11}$')]),
        ),
    ]
