# Generated by Django 4.2.3 on 2024-04-13 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abv', '0004_remove_abv_submittor_email_alter_abv_abv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abv',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
