# Generated by Django 4.2.3 on 2024-04-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abv', '0005_abv_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abv',
            old_name='user_id',
            new_name='user',
        ),
    ]
