# Generated by Django 4.2.11 on 2024-06-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abv', '0008_alter_abv_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abv',
            name='submittor_ip',
        ),
    ]
